### ISSUE TITLE
How to migrate from docker centos6 version to centos7?

### ISSUE THREAD

**Issue by xzhub** [Enalean/docker-tuleap-aio#85]
I have been running centos6(latest) docker version for a couple of months, whenever there is new docker image release, I can always upgrade without any pains, just docker-compose pull and restart will do the job. Until recently, I realized the latest version will never be updated and I have to switch to centos7 version. However, when I change the image version in my docker-compose.yml file, I see these errors;

```
tuleap2_1  | Start SSH Daemon
tuleap2_1  | Install Tuleap
tuleap2_1  | The process "'/bin/bash' '+x' '/usr/share/tuleap/tools/setup.el7.sh' '--assumeyes' '--configure' '--server-name=tuleap.local'
 '--mysql-server=localhost' '--mysql-password=2ZmsG6L7NBxe'" exceeded the timeout of 60 seconds.
tuleap2_1  | Something went wrong, here is a shell to debug:
tuleap2_1  | Initialize Mysql data store
tuleap2_1  | The command "'sudo' '-u' 'mysql' '/usr/bin/scl' 'enable' 'rh-mysql57' '--' '/opt/rh/rh-mysql57/root/usr/libexec/mysqld' '--in
itialize-insecure' '--datadir=/var/opt/rh/rh-mysql57/lib/mysql' '--user=mysql'" failed.
tuleap2_1  |
tuleap2_1  | Exit Code: 1(General error)
tuleap2_1  |
tuleap2_1  | Working directory: /
tuleap2_1  |
tuleap2_1  | Output:
tuleap2_1  | ================
tuleap2_1  |
tuleap2_1  |
tuleap2_1  | Error Output:
tuleap2_1  | ================
tuleap2_1  | 2020-02-16T13:15:06.189153Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_f
or_timestamp server option (see documentation for more details).
tuleap2_1  | 2020-02-16T13:15:06.192124Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
tuleap2_1  | 2020-02-16T13:15:06.192153Z 0 [ERROR] Aborting
tuleap2_1  |
tuleap2_1  |
tuleap2_1  | Something went wrong, here is a shell to debug:
tuleap-new_tuleap2_1 exited with code 0
```

Now I am stuck with the latest centos6 version(11.8.99), please let me know what is the best way to migrate from centos6 to centos7 docker image.

**Comment by xzhub** [comment]
Looks like the centos6 image has some updates... however, with the latest centos6 image, I still can not make it work on my previous data.  Here is my docker-compose file, appreciate if someone can show me how to migrate from the 11.8.99.214 version to the latest centos6 or centos7 docker image.

```
version: "2.1"

services:
  tuleap:
    image: enalean/tuleap-aio:latest
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tul.genowis.com
      - DB_HOST=db
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - ./tuleap-data:/data
    ports:
      - '30443:443'
      - '30022:22'
    depends_on:
      - db

  db:
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
      - ./sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
```
